# -*- coding: utf-8 -*-
"""Boosting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Di636S_0ODf5L5vosGDZVEeO3WOzik-C
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('adult.csv')
df.head(5)

df.shape

df.info()

df.isnull().sum()

df.describe()

df_missing = (df=='?').sum()
df_missing

df = df[df['workclass'] !='?']
df = df[df['occupation'] !='?']
df = df[df['native-country'] !='?']

df_missing = (df=='?').sum()
df_missing

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_cat = df.select_dtypes(include=['object'])
df_cat = df_cat.apply(le.fit_transform)
df_cat.head(3)

df = df.drop(df_cat.columns,axis=1)
df = pd.concat([df,df_cat],axis=1)
df.head()

from sklearn.model_selection import train_test_split

x = df.drop('income', axis=1)
y = df['income']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

from sklearn.ensemble import AdaBoostClassifier
model1 = AdaBoostClassifier(n_estimators=300, learning_rate=1)
model1.fit(x_train, y_train)



from sklearn.metrics import accuracy_score, confusion_matrix
x_test_pred = model1.predict(x_test)
cm = pd.DataFrame(confusion_matrix(y_test, x_test_pred), columns=['Actual -ve', 'Actual +ve'], index=['Predicted -ve', 'Predicted +ve'])
cm

from sklearn.metrics import classification_report
print(classification_report(y_test, x_test_pred))

from sklearn.ensemble import GradientBoostingClassifier
model2 = GradientBoostingClassifier(n_estimators=500, learning_rate=1, max_depth=5, subsample=0.9, min_samples_split=100, max_features='sqrt', random_state=10)
model2.fit(x_train, y_train)

x_test_pred = model2.predict(x_test)
cm = pd.DataFrame(confusion_matrix(y_test, x_test_pred), columns=['Actual -ve', 'Actual +ve'], index=['Predicted -ve', 'Predicted +ve'])
cm

print(classification_report(y_test, x_test_pred))

