# -*- coding: utf-8 -*-
"""Decision Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1113uPh5EvM6K-xA7BWp58BdYy79TfgWh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('adult.csv')
df.head(5)

df.shape

df.info()

df.isnull().sum()

df.describe()

df_missing = (df=='?').sum()
df_missing

df=df[df['workclass']!='?']
df=df[df['occupation']!='?']
df=df[df['native-country']!='?']

df_missing=(df=='?').sum()
df_missing

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_cat = df.select_dtypes(include=['object'])
df_cat = df_cat.apply(le.fit_transform)
df_cat.head(5)

df = df.drop(df_cat.columns,axis=1)
df = pd.concat([df,df_cat],axis=1)
df.head()

from sklearn.model_selection import train_test_split

x = df.drop('income', axis=1)
y = df['income']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=5)

model.fit(x_train,y_train)

from sklearn.metrics import accuracy_score

pred = model.predict(x_test)

print("Accuracy", accuracy_score(y_test,pred))

from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

