# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWR_sEV6KuooATVx9IU_cJRVwCrnEJyH
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('train.csv')
df.head(5)

df.shape

df.info()

df.isnull().sum()

df = df.drop(columns='Cabin',axis=1)

df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.isnull().sum()

sns.countplot(x='Sex',hue='Survived',data=df)

sns.countplot(x='Pclass',hue='Survived',data=df)

df.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)

df.head(5)

from sklearn.model_selection import train_test_split
X = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Survived'], axis=1)
Y = df['Survived']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score , confusion_matrix
pred = model.predict(X_test)

print("Accuracy", accuracy_score(Y_test,pred))

from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

#df.replace({'Sex':{'male': 0,'female':1} ,'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)

