# -*- coding: utf-8 -*-
"""PCA-Dimension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iP6sBKZ3-Y4FNBzdCWIiS7-5MfwBIG2V
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('adult.csv')
df.head(5)

df.shape

df.info()

df.isnull().sum()

df.describe()

df_missing = (df=='?').sum()
df_missing

df = df[df['workclass'] !='?']
df = df[df['occupation'] !='?']
df = df[df['native-country'] !='?']

df_missing = (df=='?').sum()
df_missing

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_cat = df.select_dtypes(include=['object'])
df_cat = df_cat.apply(le.fit_transform)
df_cat.head(3)

df = df.drop(df_cat.columns,axis=1)
df = pd.concat([df,df_cat],axis=1)
df.head()

x = df.drop('income', axis=1)
y = df['income']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit_transform(x)
x_scaled = scaler.transform(x)

from sklearn.model_selection import train_test_split

x_train, x_test , y_train, y_test = train_test_split(x_scaled,y,test_size=0.30)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

from sklearn.metrics import accuracy_score
pred = model.predict(x_test)

print('Accuracy',accuracy_score(y_test, pred)*100)

from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

from sklearn.decomposition import PCA
model1 = PCA()

x_pca = model1.fit_transform(x)

x_train,x_test,y_train,y_test = train_test_split(x_pca,y,test_size=0.30)

model2 = LogisticRegression()
model2.fit(x_train , y_train)

pred2 = model2.predict(x_test)

print("Accuracy :",accuracy_score(y_test, pred2))

from sklearn.metrics import classification_report
print(classification_report(y_test, pred2))



